# Novela settings
theme = "github.com/forestryio/hugo-theme-novela"

paginate = 6

[social]
twitter= "https://twitter.com/arnoldcamvas"
github= "#"
linkedin= "https://www.linkedin.com/in/arnold-campos-vasquez-772667159"
instagram = "https://www.instagram.com/arnolduae"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "Arnold Campos"